[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["express", "serverless-http", "mongoose", "cors", "dotenv", "@aws-sdk/client-s3"]
  included_files = ["package.json", "server/models/**", "server/lib/**", "api/_models/**", "api/_lib/**"]

[dev]
  command = "npm run dev"
  targetPort = 5173

# Fix Routing: Redirect API calls to the Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# Fix SPA Routing: Redirect everything else to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
